apiVersion: v1
kind: Service
metadata:
  name: {{ include "valkey.fullname" . }}
  labels:
{{ include "valkey.labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: tcp-valkey
      port: {{ .Values.service.port }}
      targetPort: 6379
  selector:
{{ include "valkey.labels" . | indent 4 }}
